/**
 * Prisma Type Stubs
 *
 * These types mirror what Prisma generates from schema.prisma.
 * In production, these are auto-generated by `npx prisma generate`.
 *
 * IMPORTANT: After cloning, run `npx prisma generate` to generate
 * the actual Prisma client with full functionality.
 */

// Enums matching schema.prisma
export enum VenueType {
  bar = 'bar',
  club = 'club',
  latin_dance = 'latin_dance'
}

export enum BusynessSource {
  provider = 'provider',
  crowd = 'crowd'
}

export enum CrowdLevel {
  dead = 'dead',
  warm = 'warm',
  busy = 'busy',
  packed = 'packed'
}

// Model types matching schema.prisma
export interface Venue {
  id: string;
  name: string;
  address: string;
  latitude: number;
  longitude: number;
  type: VenueType;
  googlePlaceId: string | null;
  description: string | null;
  phoneNumber: string | null;
  website: string | null;
  createdAt: Date;
  updatedAt: Date;
  busynessObservations?: BusynessObservation[];
  crowdReports?: CrowdReport[];
}

export interface BusynessObservation {
  id: string;
  venueId: string;
  venue?: Venue;
  source: BusynessSource;
  level: number;
  timestamp: Date;
}

export interface CrowdReport {
  id: string;
  venueId: string;
  venue?: Venue;
  level: CrowdLevel;
  tags: string[];
  browserToken: string;
  ipAddress: string;
  userAgent: string | null;
  createdAt: Date;
}

// Re-export PrismaClient type for compatibility
// The actual client is from @prisma/client after generation
export { PrismaClient } from '@prisma/client';
